kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: registry.djones.co/redirect
    registry: registry.djones.co
  when:
    branch:
    - master
